---
kind: pipeline
type: docker
name: sleep 1

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push

steps:
  - name: greeting
    image: alpine
    commands:
      - sleep 3600
---
kind: pipeline
type: docker
name: sleep 2

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push

steps:
  - name: greeting
    image: alpine
    commands:
      - sleep 3600
---
kind: pipeline
type: docker
name: sleep 3

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push

steps:
  - name: greeting
    image: alpine
    commands:
      - sleep 3600
---
kind: pipeline
type: docker
name: sleep 4

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push

steps:
  - name: greeting
    image: alpine
    commands:
      - sleep 3600
