kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world
