---
kind: pipeline
type: docker
name: sleep 1

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push

steps:
  - name: greeting
    image: alpine
    commands:
      - sleep 3600
  - name: waiting
    depends_on:
      - greeting
    image: alpine
    commands:
      - sleep 3600
